<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class brandsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('brands')->insert([
            ['name' => 'Toyota', 'vehicle_type_id' => 1, 'logo' => null],
            ['name' => 'Honda', 'vehicle_type_id' => 1, 'logo' => null],
            ['name' => 'Nissan', 'vehicle_type_id' => 1, 'logo' => null],
            ['name' => 'Ford', 'vehicle_type_id' => 1, 'logo' => null],
            ['name' => 'Chevrolet', 'vehicle_type_id' => 1, 'logo' => null],
            ['name' => 'BMW', 'vehicle_type_id' => 1, 'logo' => null],
            ['name' => 'Mercedes-Benz', 'vehicle_type_id' => 1, 'logo' => null],
            ['name' => 'Audi', 'vehicle_type_id' => 1, 'logo' => null],
            ['name' => 'Volkswagen', 'vehicle_type_id' => 1, 'logo' => null],
            ['name' => 'Hyundai', 'vehicle_type_id' => 1, 'logo' => null],
            ['name' => 'Kia', 'vehicle_type_id' => 1, 'logo' => null],
            ['name' => 'Mazda', 'vehicle_type_id' => 1, 'logo' => null],
            ['name' => 'Subaru', 'vehicle_type_id' => 1, 'logo' => null],
            ['name' => 'Lexus', 'vehicle_type_id' => 1, 'logo' => null],
            ['name' => 'Jeep', 'vehicle_type_id' => 1, 'logo' => null],
            ['name' => 'Dodge', 'vehicle_type_id' => 1, 'logo' => null],
            ['name' => 'Ram', 'vehicle_type_id' => 1, 'logo' => null],
            ['name' => 'GMC', 'vehicle_type_id' => 1, 'logo' => null],
            ['name' => 'Buick', 'vehicle_type_id' => 1, 'logo' => null],
            ['name' => 'Cadillac', 'vehicle_type_id' => 1, 'logo' => null],
            ['name' => 'Chrysler', 'vehicle_type_id' => 1, 'logo' => null],
            ['name' => 'Peugeot', 'vehicle_type_id' => 1, 'logo' => null],
            ['name' => 'Citroën', 'vehicle_type_id' => 1, 'logo' => null],
            ['name' => 'Renault', 'vehicle_type_id' => 1, 'logo' => null],
            ['name' => 'Fiat', 'vehicle_type_id' => 1, 'logo' => null],
            ['name' => 'Alfa Romeo', 'vehicle_type_id' => 1, 'logo' => null],
            ['name' => 'Maserati', 'vehicle_type_id' => 1, 'logo' => null],
            ['name' => 'Ferrari', 'vehicle_type_id' => 1, 'logo' => null],
            ['name' => 'Lamborghini', 'vehicle_type_id' => 1, 'logo' => null],
            ['name' => 'Porsche', 'vehicle_type_id' => 1, 'logo' => null],
            ['name' => 'Jaguar', 'vehicle_type_id' => 1, 'logo' => null],
            ['name' => 'Land Rover', 'vehicle_type_id' => 1, 'logo' => null],
            ['name' => 'Aston Martin', 'vehicle_type_id' => 1, 'logo' => null],
            ['name' => 'Bentley', 'vehicle_type_id' => 1, 'logo' => null],
            ['name' => 'Rolls-Royce', 'vehicle_type_id' => 1, 'logo' => null],
            ['name' => 'Mitsubishi', 'vehicle_type_id' => 1, 'logo' => null],
            ['name' => 'Suzuki', 'vehicle_type_id' => 1, 'logo' => null],
            ['name' => 'Isuzu', 'vehicle_type_id' => 1, 'logo' => null],
            ['name' => 'Tesla', 'vehicle_type_id' => 1, 'logo' => null],
            ['name' => 'Rivian', 'vehicle_type_id' => 1, 'logo' => null],
            ['name' => 'Lucid', 'vehicle_type_id' => 1, 'logo' => null],
            ['name' => 'Polestar', 'vehicle_type_id' => 1, 'logo' => null],
            ['name' => 'BYD', 'vehicle_type_id' => 1, 'logo' => null],
            ['name' => 'Geely', 'vehicle_type_id' => 1, 'logo' => null],
            ['name' => 'Great Wall', 'vehicle_type_id' => 1, 'logo' => null],
            ['name' => 'Chery', 'vehicle_type_id' => 1, 'logo' => null],
            ['name' => 'Saab', 'vehicle_type_id' => 1, 'logo' => null],
            ['name' => 'Mini', 'vehicle_type_id' => 1, 'logo' => null],
            ['name' => 'Smart', 'vehicle_type_id' => 1, 'logo' => null],

            ['name' => 'Ducati', 'vehicle_type_id' => 2, 'logo' => null],
            ['name' => 'Yamaha', 'vehicle_type_id' => 2, 'logo' => null],
            ['name' => 'Aprilia', 'vehicle_type_id' => 2, 'logo' => null],
            ['name' => 'Harley-Davidson', 'vehicle_type_id' => 2, 'logo' => null],
            ['name' => 'Kawasaki', 'vehicle_type_id' => 2, 'logo' => null],
            ['name' => 'Suzuki Motorcycles', 'vehicle_type_id' => 2, 'logo' => null],
            ['name' => 'Honda Motorcycles', 'vehicle_type_id' => 2, 'logo' => null],
            ['name' => 'BMW Motorrad', 'vehicle_type_id' => 2, 'logo' => null],
            ['name' => 'KTM', 'vehicle_type_id' => 2, 'logo' => null],
            ['name' => 'Husqvarna', 'vehicle_type_id' => 2, 'logo' => null],
            ['name' => 'Triumph', 'vehicle_type_id' => 2, 'logo' => null],
            ['name' => 'Moto Guzzi', 'vehicle_type_id' => 2, 'logo' => null],
            ['name' => 'Piaggio', 'vehicle_type_id' => 2, 'logo' => null],
            ['name' => 'Vespa', 'vehicle_type_id' => 2, 'logo' => null],
            ['name' => 'Royal Enfield', 'vehicle_type_id' => 2, 'logo' => null],
            ['name' => 'Indian Motorcycles', 'vehicle_type_id' => 2, 'logo' => null],
            ['name' => 'MV Agusta', 'vehicle_type_id' => 2, 'logo' => null],
            ['name' => 'Bimota', 'vehicle_type_id' => 2, 'logo' => null],
            ['name' => 'Benelli', 'vehicle_type_id' => 2, 'logo' => null],
            ['name' => 'Cagiva', 'vehicle_type_id' => 2, 'logo' => null],
            ['name' => 'Derbi', 'vehicle_type_id' => 2, 'logo' => null],
            ['name' => 'GasGas', 'vehicle_type_id' => 2, 'logo' => null],
            ['name' => 'Sherco', 'vehicle_type_id' => 2, 'logo' => null],
            ['name' => 'Beta', 'vehicle_type_id' => 2, 'logo' => null],
            ['name' => 'Zero Motorcycles', 'vehicle_type_id' => 2, 'logo' => null],
            ['name' => 'LiveWire', 'vehicle_type_id' => 2, 'logo' => null],
            ['name' => 'Energica', 'vehicle_type_id' => 2, 'logo' => null],

            ['name' => 'Scania', 'vehicle_type_id' => 3, 'logo' => null],
            ['name' => 'Volvo Trucks', 'vehicle_type_id' => 3, 'logo' => null],
            ['name' => 'Man', 'vehicle_type_id' => 3, 'logo' => null],
            ['name' => 'Mercedes-Benz Trucks', 'vehicle_type_id' => 3, 'logo' => null],
            ['name' => 'DAF', 'vehicle_type_id' => 3, 'logo' => null],
            ['name' => 'Iveco', 'vehicle_type_id' => 3, 'logo' => null],
            ['name' => 'Renault Trucks', 'vehicle_type_id' => 3, 'logo' => null],
            ['name' => 'Peterbilt', 'vehicle_type_id' => 3, 'logo' => null],
            ['name' => 'Kenworth', 'vehicle_type_id' => 3, 'logo' => null],
            ['name' => 'Mack', 'vehicle_type_id' => 3, 'logo' => null],
            ['name' => 'Freightliner', 'vehicle_type_id' => 3, 'logo' => null],
            ['name' => 'Western Star', 'vehicle_type_id' => 3, 'logo' => null],
            ['name' => 'International', 'vehicle_type_id' => 3, 'logo' => null],
            ['name' => 'Hino', 'vehicle_type_id' => 3, 'logo' => null],
            ['name' => 'Isuzu Trucks', 'vehicle_type_id' => 3, 'logo' => null],
            ['name' => 'UD Trucks', 'vehicle_type_id' => 3, 'logo' => null],
            ['name' => 'Fuso', 'vehicle_type_id' => 3, 'logo' => null],
            ['name' => 'Tatra', 'vehicle_type_id' => 3, 'logo' => null],
            ['name' => 'Kamaz', 'vehicle_type_id' => 3, 'logo' => null],
            ['name' => 'GAZ', 'vehicle_type_id' => 3, 'logo' => null],

            ['name' => 'Yamaha Marine', 'vehicle_type_id' => 4, 'logo' => null],
            ['name' => 'Mercury Marine', 'vehicle_type_id' => 4, 'logo' => null],
            ['name' => 'Suzuki Marine', 'vehicle_type_id' => 4, 'logo' => null],
            ['name' => 'Honda Marine', 'vehicle_type_id' => 4, 'logo' => null],
            ['name' => 'Volvo Penta', 'vehicle_type_id' => 4, 'logo' => null],
            ['name' => 'Cummins Marine', 'vehicle_type_id' => 4, 'logo' => null],
            ['name' => 'CAT Marine', 'vehicle_type_id' => 4, 'logo' => null],
            ['name' => 'MAN Marine', 'vehicle_type_id' => 4, 'logo' => null],
            ['name' => 'MTU', 'vehicle_type_id' => 4, 'logo' => null],
            ['name' => 'Scania Marine', 'vehicle_type_id' => 4, 'logo' => null],
            ['name' => 'John Deere Marine', 'vehicle_type_id' => 4, 'logo' => null],
            ['name' => 'Perkins Marine', 'vehicle_type_id' => 4, 'logo' => null],
            ['name' => 'Boston Whaler', 'vehicle_type_id' => 4, 'logo' => null],
            ['name' => 'Sea Ray', 'vehicle_type_id' => 4, 'logo' => null],
            ['name' => 'Bayliner', 'vehicle_type_id' => 4, 'logo' => null],
            ['name' => 'Grady-White', 'vehicle_type_id' => 4, 'logo' => null],
            ['name' => 'Parker Boats', 'vehicle_type_id' => 4, 'logo' => null],
            ['name' => 'MasterCraft', 'vehicle_type_id' => 4, 'logo' => null],
            ['name' => 'Malibu Boats', 'vehicle_type_id' => 4, 'logo' => null],
            ['name' => 'Beneteau', 'vehicle_type_id' => 4, 'logo' => null],
            ['name' => 'Jeanneau', 'vehicle_type_id' => 4, 'logo' => null],
            ['name' => 'Bavaria', 'vehicle_type_id' => 4, 'logo' => null],
            ['name' => 'Hanse', 'vehicle_type_id' => 4, 'logo' => null],

            ['name' => 'Trek', 'vehicle_type_id' => 5, 'logo' => null],
            ['name' => 'Giant', 'vehicle_type_id' => 5, 'logo' => null],
            ['name' => 'Specialized', 'vehicle_type_id' => 5, 'logo' => null],
            ['name' => 'Cannondale', 'vehicle_type_id' => 5, 'logo' => null],
            ['name' => 'Bianchi', 'vehicle_type_id' => 5, 'logo' => null],
            ['name' => 'Pinarello', 'vehicle_type_id' => 5, 'logo' => null],
            ['name' => 'Colnago', 'vehicle_type_id' => 5, 'logo' => null],
            ['name' => 'Cervelo', 'vehicle_type_id' => 5, 'logo' => null],
            ['name' => 'Scott', 'vehicle_type_id' => 5, 'logo' => null],
            ['name' => 'Merida', 'vehicle_type_id' => 5, 'logo' => null],
            ['name' => 'Orbea', 'vehicle_type_id' => 5, 'logo' => null],
            ['name' => 'BH Bikes', 'vehicle_type_id' => 5, 'logo' => null],
            ['name' => 'Cube', 'vehicle_type_id' => 5, 'logo' => null],
            ['name' => 'Focus', 'vehicle_type_id' => 5, 'logo' => null],
            ['name' => 'Felt', 'vehicle_type_id' => 5, 'logo' => null],
            ['name' => 'Salsa', 'vehicle_type_id' => 5, 'logo' => null],
            ['name' => 'Surly', 'vehicle_type_id' => 5, 'logo' => null],
            ['name' => 'Raleigh', 'vehicle_type_id' => 5, 'logo' => null],
            ['name' => 'Diamondback', 'vehicle_type_id' => 5, 'logo' => null],
            ['name' => 'Schwinn', 'vehicle_type_id' => 5, 'logo' => null],
            ['name' => 'Mongoose', 'vehicle_type_id' => 5, 'logo' => null],
            ['name' => 'GT Bicycles', 'vehicle_type_id' => 5, 'logo' => null],
            ['name' => 'Haro', 'vehicle_type_id' => 5, 'logo' => null],
            ['name' => 'Santa Cruz', 'vehicle_type_id' => 5, 'logo' => null],
            ['name' => 'Yeti', 'vehicle_type_id' => 5, 'logo' => null],
            ['name' => 'Pivot', 'vehicle_type_id' => 5, 'logo' => null],
            ['name' => 'Evil Bikes', 'vehicle_type_id' => 5, 'logo' => null],
            ['name' => 'Intense', 'vehicle_type_id' => 5, 'logo' => null],
            ['name' => 'Niner', 'vehicle_type_id' => 5, 'logo' => null],
            ['name' => 'Kona', 'vehicle_type_id' => 5, 'logo' => null],
            ['name' => 'Norco', 'vehicle_type_id' => 5, 'logo' => null],
            ['name' => 'Rocky Mountain', 'vehicle_type_id' => 5, 'logo' => null],
            ['name' => 'Devinci', 'vehicle_type_id' => 5, 'logo' => null],
            ['name' => 'Electra', 'vehicle_type_id' => 5, 'logo' => null],
            ['name' => 'Tern', 'vehicle_type_id' => 5, 'logo' => null],
            ['name' => 'Brompton', 'vehicle_type_id' => 5, 'logo' => null],
            ['name' => 'Dahon', 'vehicle_type_id' => 5, 'logo' => null],
            ['name' => 'Riese & Müller', 'vehicle_type_id' => 5, 'logo' => null],
            ['name' => 'Haibike', 'vehicle_type_id' => 5, 'logo' => null],
        ]);
    }
}