<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class countriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('countries')->insert([
            ['name' => 'Morocco'],
            ['name' => 'Algeria'],
            ['name' => 'Tunisia'],
            ['name' => 'Egypt'],
            ['name' => 'South Africa'],
            ['name' => 'Nigeria'],
            ['name' => 'Kenya'],
            ['name' => 'Ghana'],
            ['name' => 'Ethiopia'],
            ['name' => 'Angola'],
            ['name' => 'Mozambique'],
            ['name' => 'Zimbabwe'],
            ['name' => 'Zambia'],
            ['name' => 'Botswana'],
            ['name' => 'Namibia'],
            ['name' => 'Senegal'],
            ['name' => 'Ivory Coast'],
            ['name' => 'Cameroon'],
            ['name' => 'Uganda'],
            ['name' => 'Tanzania'],
            ['name' => 'Sudan'],
            ['name' => 'Libya'],
            ['name' => 'Mauritania'],
            ['name' => 'Mali'],
            ['name' => 'Niger'],
            ['name' => 'Chad'],
            ['name' => 'Central African Republic'],
            ['name' => 'Democratic Republic of the Congo'],
            ['name' => 'Republic of the Congo'],
            ['name' => 'Gabon'],
            ['name' => 'Equatorial Guinea'],
            ['name' => 'Somalia'],
            ['name' => 'Djibouti'],
            ['name' => 'Eritrea'],
            ['name' => 'Rwanda'],
            ['name' => 'Burundi'],
            ['name' => 'Malawi'],
            ['name' => 'Madagascar'],
            ['name' => 'Mauritius'],
            ['name' => 'Seychelles'],
            ['name' => 'Comoros'],
            ['name' => 'Cape Verde'],
            ['name' => 'Sao Tome and Principe'],
            ['name' => 'Liberia'],
            ['name' => 'Sierra Leone'],
            ['name' => 'Guinea'],
            ['name' => 'Guinea-Bissau'],
            ['name' => 'Gambia'],
            ['name' => 'Togo'],
            ['name' => 'Benin'],
            ['name' => 'Burkina Faso'],

            ['name' => 'United Kingdom'],
            ['name' => 'France'],
            ['name' => 'Germany'],
            ['name' => 'Spain'],
            ['name' => 'Portugal'],
            ['name' => 'Italy'],
            ['name' => 'Netherlands'],
            ['name' => 'Belgium'],
            ['name' => 'Switzerland'],
            ['name' => 'Austria'],
            ['name' => 'Sweden'],
            ['name' => 'Norway'],
            ['name' => 'Denmark'],
            ['name' => 'Finland'],
            ['name' => 'Ireland'],
            ['name' => 'Poland'],
            ['name' => 'Czech Republic'],
            ['name' => 'Slovakia'],
            ['name' => 'Hungary'],
            ['name' => 'Romania'],
            ['name' => 'Bulgaria'],
            ['name' => 'Greece'],
            ['name' => 'Turkey'],
            ['name' => 'Russia'],
            ['name' => 'Ukraine'],
            ['name' => 'Belarus'],
            ['name' => 'Moldova'],
            ['name' => 'Estonia'],
            ['name' => 'Latvia'],
            ['name' => 'Lithuania'],
            ['name' => 'Slovenia'],
            ['name' => 'Croatia'],
            ['name' => 'Bosnia and Herzegovina'],
            ['name' => 'Serbia'],
            ['name' => 'Montenegro'],
            ['name' => 'North Macedonia'],
            ['name' => 'Albania'],
            ['name' => 'Kosovo'],
            ['name' => 'Iceland'],
            ['name' => 'Luxembourg'],
            ['name' => 'Malta'],
            ['name' => 'Cyprus'],

            ['name' => 'United States'],
            ['name' => 'Canada'],
            ['name' => 'Mexico'],
            ['name' => 'Cuba'],
            ['name' => 'Jamaica'],
            ['name' => 'Dominican Republic'],
            ['name' => 'Puerto Rico'],
            ['name' => 'Haiti'],
            ['name' => 'Trinidad and Tobago'],
            ['name' => 'Bahamas'],
            ['name' => 'Barbados'],
            ['name' => 'Belize'],
            ['name' => 'Costa Rica'],
            ['name' => 'El Salvador'],
            ['name' => 'Guatemala'],
            ['name' => 'Honduras'],
            ['name' => 'Nicaragua'],
            ['name' => 'Panama'],

            ['name' => 'Brazil'],
            ['name' => 'Argentina'],
            ['name' => 'Chile'],
            ['name' => 'Colombia'],
            ['name' => 'Peru'],
            ['name' => 'Venezuela'],
            ['name' => 'Uruguay'],
            ['name' => 'Paraguay'],
            ['name' => 'Bolivia'],
            ['name' => 'Ecuador'],
            ['name' => 'Guyana'],
            ['name' => 'Suriname'],

            ['name' => 'China'],
            ['name' => 'Japan'],
            ['name' => 'India'],
            ['name' => 'South Korea'],
            ['name' => 'Singapore'],
            ['name' => 'Malaysia'],
            ['name' => 'Indonesia'],
            ['name' => 'Philippines'],
            ['name' => 'Vietnam'],
            ['name' => 'Thailand'],
            ['name' => 'Saudi Arabia'],
            ['name' => 'United Arab Emirates'],
            ['name' => 'Kuwait'],
            ['name' => 'Qatar'],
            ['name' => 'Oman'],
            ['name' => 'Bahrain'],
            ['name' => 'Pakistan'],
            ['name' => 'Bangladesh'],
            ['name' => 'Sri Lanka'],
            ['name' => 'Nepal'],
            ['name' => 'Taiwan'],
            ['name' => 'Hong Kong'],
            ['name' => 'Israel'],
            ['name' => 'Iran'],
            ['name' => 'Iraq'],
            ['name' => 'Syria'],
            ['name' => 'Jordan'],
            ['name' => 'Lebanon'],
            ['name' => 'Yemen'],
            ['name' => 'Afghanistan'],
            ['name' => 'Myanmar'],
            ['name' => 'Cambodia'],
            ['name' => 'Laos'],
            ['name' => 'Mongolia'],
            ['name' => 'Uzbekistan'],
            ['name' => 'Kazakhstan'],
            ['name' => 'Azerbaijan'],
            ['name' => 'Georgia'],
            ['name' => 'Armenia'],

            ['name' => 'Australia'],
            ['name' => 'New Zealand'],
            ['name' => 'Fiji'],
            ['name' => 'Papua New Guinea'],
            ['name' => 'Solomon Islands'],
            ['name' => 'Vanuatu'],
            ['name' => 'Samoa'],
            ['name' => 'Tonga'],

            ['name' => 'Monaco'],
            ['name' => 'Andorra'],
            ['name' => 'San Marino'],
            ['name' => 'Vatican City'],
            ['name' => 'Liechtenstein'],

            ['name' => 'Aruba'],
            ['name' => 'Curaçao'],
            ['name' => 'Cayman Islands'],
            ['name' => 'Bermuda'],
            ['name' => 'St. Lucia'],
            ['name' => 'St. Vincent and the Grenadines'],
            ['name' => 'Grenada'],
            ['name' => 'Antigua and Barbuda'],
            ['name' => 'Dominica'],
            ['name' => 'St. Kitts and Nevis'],
        ]);
    }
}