<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ModelSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('vehicle_models')->insert([
            ['name' => 'Corolla', 'brand_id' => 1],
            ['name' => 'Camry', 'brand_id' => 1],
            ['name' => 'RAV4', 'brand_id' => 1],
            ['name' => 'Highlander', 'brand_id' => 1],
            ['name' => 'Tacoma', 'brand_id' => 1],
            ['name' => 'Tundra', 'brand_id' => 1],
            ['name' => 'Sienna', 'brand_id' => 1],
            ['name' => 'Prius', 'brand_id' => 1],
            ['name' => '4Runner', 'brand_id' => 1],
            ['name' => 'Land Cruiser', 'brand_id' => 1],
            ['name' => 'Supra', 'brand_id' => 1],

            ['name' => 'Accord', 'brand_id' => 2],
            ['name' => 'Civic', 'brand_id' => 2],
            ['name' => 'CR-V', 'brand_id' => 2],
            ['name' => 'Pilot', 'brand_id' => 2],
            ['name' => 'Odyssey', 'brand_id' => 2],
            ['name' => 'HR-V', 'brand_id' => 2],
            ['name' => 'Passport', 'brand_id' => 2],
            ['name' => 'Ridgeline', 'brand_id' => 2],

            ['name' => 'Altima', 'brand_id' => 3],
            ['name' => 'Maxima', 'brand_id' => 3],
            ['name' => 'Rogue', 'brand_id' => 3],
            ['name' => 'Pathfinder', 'brand_id' => 3],
            ['name' => 'Armada', 'brand_id' => 3],
            ['name' => 'Titan', 'brand_id' => 3],
            ['name' => 'Leaf', 'brand_id' => 3],
            ['name' => 'Kicks', 'brand_id' => 3],
            ['name' => 'Murano', 'brand_id' => 3],

            ['name' => 'F-150', 'brand_id' => 4],
            ['name' => 'Mustang', 'brand_id' => 4],
            ['name' => 'Escape', 'brand_id' => 4],
            ['name' => 'Explorer', 'brand_id' => 4],
            ['name' => 'Expedition', 'brand_id' => 4],
            ['name' => 'Ranger', 'brand_id' => 4],
            ['name' => 'Bronco', 'brand_id' => 4],
            ['name' => 'Edge', 'brand_id' => 4],
            ['name' => 'Focus', 'brand_id' => 4],

            ['name' => 'Silverado', 'brand_id' => 5],
            ['name' => 'Camaro', 'brand_id' => 5],
            ['name' => 'Equinox', 'brand_id' => 5],
            ['name' => 'Tahoe', 'brand_id' => 5],
            ['name' => 'Suburban', 'brand_id' => 5],
            ['name' => 'Traverse', 'brand_id' => 5],
            ['name' => 'Colorado', 'brand_id' => 5],
            ['name' => 'Malibu', 'brand_id' => 5],
            ['name' => '3 Series', 'brand_id' => 6],
            ['name' => '5 Series', 'brand_id' => 6],
            ['name' => '7 Series', 'brand_id' => 6],
            ['name' => 'X3', 'brand_id' => 6],
            ['name' => 'X5', 'brand_id' => 6],
            ['name' => 'X7', 'brand_id' => 6],
            ['name' => 'M3', 'brand_id' => 6],
            ['name' => 'M4', 'brand_id' => 6],
            ['name' => 'i4', 'brand_id' => 6],
            ['name' => 'iX', 'brand_id' => 6],


            ['name' => 'C-Class', 'brand_id' => 7],
            ['name' => 'E-Class', 'brand_id' => 7],
            ['name' => 'S-Class', 'brand_id' => 7],
            ['name' => 'GLC', 'brand_id' => 7],
            ['name' => 'GLE', 'brand_id' => 7],
            ['name' => 'GLS', 'brand_id' => 7],
            ['name' => 'G-Class', 'brand_id' => 7],
            ['name' => 'EQS', 'brand_id' => 7],
            ['name' => 'EQE', 'brand_id' => 7],
            ['name' => 'AMG GT', 'brand_id' => 7],

            ['name' => 'A3', 'brand_id' => 8],
            ['name' => 'A4', 'brand_id' => 8],
            ['name' => 'A6', 'brand_id' => 8],
            ['name' => 'A8', 'brand_id' => 8],
            ['name' => 'Q3', 'brand_id' => 8],
            ['name' => 'Q5', 'brand_id' => 8],
            ['name' => 'Q7', 'brand_id' => 8],
            ['name' => 'Q8', 'brand_id' => 8],
            ['name' => 'e-tron', 'brand_id' => 8],
            ['name' => 'RS6', 'brand_id' => 8],

            ['name' => 'Golf', 'brand_id' => 9],
            ['name' => 'Jetta', 'brand_id' => 9],
            ['name' => 'Passat', 'brand_id' => 9],
            ['name' => 'Tiguan', 'brand_id' => 9],
            ['name' => 'Atlas', 'brand_id' => 9],
            ['name' => 'ID.4', 'brand_id' => 9],
            ['name' => 'Taos', 'brand_id' => 9],
            ['name' => 'GTI', 'brand_id' => 9],
            ['name' => 'R', 'brand_id' => 9],

            ['name' => 'Elantra', 'brand_id' => 10],
            ['name' => 'Sonata', 'brand_id' => 10],
            ['name' => 'Tucson', 'brand_id' => 10],
            ['name' => 'Santa Fe', 'brand_id' => 10],
            ['name' => 'Palisade', 'brand_id' => 10],
            ['name' => 'Kona', 'brand_id' => 10],
            ['name' => 'Ioniq', 'brand_id' => 10],
            ['name' => 'Venue', 'brand_id' => 10],

            ['name' => 'Optima', 'brand_id' => 11],
            ['name' => 'Sportage', 'brand_id' => 11],
            ['name' => 'Sorento', 'brand_id' => 11],
            ['name' => 'Telluride', 'brand_id' => 11],
            ['name' => 'Stinger', 'brand_id' => 11],
            ['name' => 'Soul', 'brand_id' => 11],
            ['name' => 'Rio', 'brand_id' => 11],
            ['name' => 'Niro', 'brand_id' => 11],

            ['name' => 'Mazda3', 'brand_id' => 12],
            ['name' => 'Mazda6', 'brand_id' => 12],
            ['name' => 'CX-5', 'brand_id' => 12],
            ['name' => 'CX-9', 'brand_id' => 12],
            ['name' => 'MX-5 Miata', 'brand_id' => 12],
            ['name' => 'CX-30', 'brand_id' => 12],
            ['name' => 'CX-50', 'brand_id' => 12],

            ['name' => 'Outback', 'brand_id' => 13],
            ['name' => 'Forester', 'brand_id' => 13],
            ['name' => 'Crosstrek', 'brand_id' => 13],
            ['name' => 'Ascent', 'brand_id' => 13],
            ['name' => 'Impreza', 'brand_id' => 13],
            ['name' => 'Legacy', 'brand_id' => 13],
            ['name' => 'BRZ', 'brand_id' => 13],

            ['name' => 'ES', 'brand_id' => 14],
            ['name' => 'IS', 'brand_id' => 14],
            ['name' => 'RX', 'brand_id' => 14],
            ['name' => 'NX', 'brand_id' => 14],
            ['name' => 'GX', 'brand_id' => 14],
            ['name' => 'LX', 'brand_id' => 14],
            ['name' => 'LC', 'brand_id' => 14],
            ['name' => 'UX', 'brand_id' => 14],
            ['name' => 'RZ', 'brand_id' => 14],

            ['name' => 'Wrangler', 'brand_id' => 15],
            ['name' => 'Grand Cherokee', 'brand_id' => 15],
            ['name' => 'Cherokee', 'brand_id' => 15],
            ['name' => 'Compass', 'brand_id' => 15],
            ['name' => 'Renegade', 'brand_id' => 15],
            ['name' => 'Gladiator', 'brand_id' => 15],
            ['name' => 'Wagoneer', 'brand_id' => 15],

            ['name' => 'Challenger', 'brand_id' => 16],
            ['name' => 'Charger', 'brand_id' => 16],
            ['name' => 'Durango', 'brand_id' => 16],
            ['name' => 'Journey', 'brand_id' => 16],
            ['name' => 'Magnum', 'brand_id' => 16],

            ['name' => '1500', 'brand_id' => 17],
            ['name' => '2500', 'brand_id' => 17],
            ['name' => '3500', 'brand_id' => 17],
            ['name' => 'ProMaster', 'brand_id' => 17],

            ['name' => 'Model S', 'brand_id' => 38],
            ['name' => 'Model 3', 'brand_id' => 38],
            ['name' => 'Model X', 'brand_id' => 38],
            ['name' => 'Model Y', 'brand_id' => 38],
            ['name' => 'Cybertruck', 'brand_id' => 38],
            ['name' => 'Roadster', 'brand_id' => 38],

            ['name' => '911', 'brand_id' => 30],
            ['name' => 'Cayenne', 'brand_id' => 30],
            ['name' => 'Macan', 'brand_id' => 30],
            ['name' => 'Panamera', 'brand_id' => 30],
            ['name' => 'Taycan', 'brand_id' => 30],
            ['name' => 'Boxster', 'brand_id' => 30],
            ['name' => 'Cayman', 'brand_id' => 30],

            ['name' => 'F8 Tributo', 'brand_id' => 28],
            ['name' => 'SF90 Stradale', 'brand_id' => 28],
            ['name' => 'Portofino', 'brand_id' => 28],
            ['name' => 'Roma', 'brand_id' => 28],
            ['name' => '812 Superfast', 'brand_id' => 28],
            ['name' => 'Purosangue', 'brand_id' => 28],


            ['name' => 'Huracán', 'brand_id' => 29],
            ['name' => 'Aventador', 'brand_id' => 29],
            ['name' => 'Urus', 'brand_id' => 29],
            ['name' => 'Revuelto', 'brand_id' => 29],
            ['name' => 'Gallardo', 'brand_id' => 29],

            ['name' => 'Range Rover', 'brand_id' => 32],
            ['name' => 'Range Rover Sport', 'brand_id' => 32],
            ['name' => 'Discovery', 'brand_id' => 32],
            ['name' => 'Defender', 'brand_id' => 32],
            ['name' => 'Evoque', 'brand_id' => 32],
            ['name' => 'Velar', 'brand_id' => 32],

            ['name' => 'F-Type', 'brand_id' => 31],
            ['name' => 'XF', 'brand_id' => 31],
            ['name' => 'XE', 'brand_id' => 31],
            ['name' => 'F-Pace', 'brand_id' => 31],
            ['name' => 'E-Pace', 'brand_id' => 31],
            ['name' => 'I-Pace', 'brand_id' => 31],

            ['name' => 'Outlander', 'brand_id' => 35],
            ['name' => 'Eclipse Cross', 'brand_id' => 35],
            ['name' => 'Pajero', 'brand_id' => 35],
            ['name' => 'ASX', 'brand_id' => 35],
            ['name' => 'Lancer', 'brand_id' => 35],


            ['name' => 'Swift', 'brand_id' => 36],
            ['name' => 'Vitara', 'brand_id' => 36],
            ['name' => 'Jimny', 'brand_id' => 36],
            ['name' => 'S-Cross', 'brand_id' => 36],
            ['name' => 'Baleno', 'brand_id' => 36],

            ['name' => 'Monster', 'brand_id' => 51],
            ['name' => 'Panigale', 'brand_id' => 51],
            ['name' => 'Multistrada', 'brand_id' => 51],
            ['name' => 'Scrambler', 'brand_id' => 51],
            ['name' => 'Diavel', 'brand_id' => 51],
            ['name' => 'Streetfighter', 'brand_id' => 51],

            ['name' => 'YZF-R1', 'brand_id' => 52],
            ['name' => 'YZF-R6', 'brand_id' => 52],
            ['name' => 'MT-07', 'brand_id' => 52],
            ['name' => 'MT-09', 'brand_id' => 52],
            ['name' => 'Tracer 9', 'brand_id' => 52],
            ['name' => 'Tenere 700', 'brand_id' => 52],
            ['name' => 'XSR700', 'brand_id' => 52],

            ['name' => 'Street Glide', 'brand_id' => 54],
            ['name' => 'Road King', 'brand_id' => 54],
            ['name' => 'Fat Boy', 'brand_id' => 54],
            ['name' => 'Iron 883', 'brand_id' => 54],
            ['name' => 'Sportster', 'brand_id' => 54],
            ['name' => 'Pan America', 'brand_id' => 54],

            ['name' => 'Ninja ZX-10R', 'brand_id' => 55],
            ['name' => 'Ninja ZX-6R', 'brand_id' => 55],
            ['name' => 'Z900', 'brand_id' => 55],
            ['name' => 'Versys 650', 'brand_id' => 55],
            ['name' => 'Vulcan', 'brand_id' => 55],
            ['name' => 'KLR650', 'brand_id' => 55],

            ['name' => 'GSX-R1000', 'brand_id' => 56],
            ['name' => 'GSX-R750', 'brand_id' => 56],
            ['name' => 'V-Strom 650', 'brand_id' => 56],
            ['name' => 'Hayabusa', 'brand_id' => 56],
            ['name' => 'SV650', 'brand_id' => 56],

            ['name' => 'CBR1000RR-R', 'brand_id' => 57],
            ['name' => 'CBR600RR', 'brand_id' => 57],
            ['name' => 'CRF450L', 'brand_id' => 57],
            ['name' => 'Africa Twin', 'brand_id' => 57],
            ['name' => 'Rebel 500', 'brand_id' => 57],
            ['name' => 'NC750X', 'brand_id' => 57],

            ['name' => 'R 1250 GS', 'brand_id' => 58],
            ['name' => 'S 1000 RR', 'brand_id' => 58],
            ['name' => 'F 850 GS', 'brand_id' => 58],
            ['name' => 'K 1600 GT', 'brand_id' => 58],
            ['name' => 'R nineT', 'brand_id' => 58],

            ['name' => '1290 Super Duke R', 'brand_id' => 59],
            ['name' => '790 Duke', 'brand_id' => 59],
            ['name' => '890 Adventure', 'brand_id' => 59],
            ['name' => '450 EXC-F', 'brand_id' => 59],
            ['name' => 'RC 390', 'brand_id' => 59],

            ['name' => 'Street Triple', 'brand_id' => 61],
            ['name' => 'Tiger 900', 'brand_id' => 61],
            ['name' => 'Bonneville T120', 'brand_id' => 61],
            ['name' => 'Speed Triple', 'brand_id' => 61],
            ['name' => 'Scrambler 1200', 'brand_id' => 61],

            ['name' => 'Primavera', 'brand_id' => 64],
            ['name' => 'Sprint', 'brand_id' => 64],
            ['name' => 'GTS 300', 'brand_id' => 64],
            ['name' => 'Elettrica', 'brand_id' => 64],

            ['name' => 'Classic 350', 'brand_id' => 65],
            ['name' => 'Interceptor 650', 'brand_id' => 65],
            ['name' => 'Himalayan', 'brand_id' => 65],
            ['name' => 'Meteor 350', 'brand_id' => 65],

            ['name' => 'R-Series', 'brand_id' => 78],
            ['name' => 'S-Series', 'brand_id' => 78],
            ['name' => 'G-Series', 'brand_id' => 78],
            ['name' => 'P-Series', 'brand_id' => 78],

            ['name' => 'FH', 'brand_id' => 79],
            ['name' => 'FM', 'brand_id' => 79],
            ['name' => 'FL', 'brand_id' => 79],
            ['name' => 'FE', 'brand_id' => 79],

            ['name' => 'TGX', 'brand_id' => 80],
            ['name' => 'TGS', 'brand_id' => 80],
            ['name' => 'TGL', 'brand_id' => 80],
            ['name' => 'TGM', 'brand_id' => 80],

            ['name' => 'Actros', 'brand_id' => 81],
            ['name' => 'Arocs', 'brand_id' => 81],
            ['name' => 'Antos', 'brand_id' => 81],
            ['name' => 'Unimog', 'brand_id' => 81],

            ['name' => 'XF', 'brand_id' => 82],
            ['name' => 'CF', 'brand_id' => 82],
            ['name' => 'LF', 'brand_id' => 82],

            ['name' => 'S-Way', 'brand_id' => 83],
            ['name' => 'Daily', 'brand_id' => 83],
            ['name' => 'Eurocargo', 'brand_id' => 83],

            ['name' => '379', 'brand_id' => 86],
            ['name' => '389', 'brand_id' => 86],
            ['name' => '579', 'brand_id' => 86],
            ['name' => '567', 'brand_id' => 86],

            ['name' => 'T680', 'brand_id' => 87],
            ['name' => 'T880', 'brand_id' => 87],
            ['name' => 'W900', 'brand_id' => 87],
            ['name' => 'T370', 'brand_id' => 87],

            ['name' => 'Cascadia', 'brand_id' => 89],
            ['name' => 'M2', 'brand_id' => 89],
            ['name' => 'FL', 'brand_id' => 89],
            ['name' => 'Coronado', 'brand_id' => 89],

            ['name' => 'F-Series', 'brand_id' => 98],
            ['name' => 'V-Max SHO', 'brand_id' => 98],
            ['name' => 'XTO Offshore', 'brand_id' => 98],
            ['name' => 'Jet Drive', 'brand_id' => 98],

            ['name' => 'Verado', 'brand_id' => 99],
            ['name' => 'Pro XS', 'brand_id' => 99],
            ['name' => 'FourStroke', 'brand_id' => 99],
            ['name' => 'SeaPro', 'brand_id' => 99],

            ['name' => 'DF Series', 'brand_id' => 100],
            ['name' => 'Twin', 'brand_id' => 100],
            ['name' => 'Triple', 'brand_id' => 100],

            ['name' => 'BF Series', 'brand_id' => 101],
            ['name' => 'V-Tech', 'brand_id' => 101],

            ['name' => 'Domane', 'brand_id' => 118],
            ['name' => 'Emonda', 'brand_id' => 118],
            ['name' => 'Madone', 'brand_id' => 118],
            ['name' => 'Fuel EX', 'brand_id' => 118],
            ['name' => 'Marlin', 'brand_id' => 118],
            ['name' => 'Roscoe', 'brand_id' => 118],

            ['name' => 'Defy', 'brand_id' => 119],
            ['name' => 'TCR', 'brand_id' => 119],
            ['name' => 'Propel', 'brand_id' => 119],
            ['name' => 'Trinity', 'brand_id' => 119],
            ['name' => 'Reign', 'brand_id' => 119],


            ['name' => 'Tarmac', 'brand_id' => 120],
            ['name' => 'Roubaix', 'brand_id' => 120],
            ['name' => 'Stumpjumper', 'brand_id' => 120],
            ['name' => 'Rockhopper', 'brand_id' => 120],
            ['name' => 'S-Works', 'brand_id' => 120],

            ['name' => 'SuperSix EVO', 'brand_id' => 121],
            ['name' => 'SystemSix', 'brand_id' => 121],
            ['name' => 'Scalpel', 'brand_id' => 121],
            ['name' => 'Trail', 'brand_id' => 121],

            ['name' => 'Oltre', 'brand_id' => 122],
            ['name' => 'Specialissima', 'brand_id' => 122],
            ['name' => 'Infinito', 'brand_id' => 122],
            ['name' => 'Methanol', 'brand_id' => 122],

            ['name' => 'Dogma F', 'brand_id' => 123],
            ['name' => 'Prince', 'brand_id' => 123],
            ['name' => 'Gan', 'brand_id' => 123],
            ['name' => 'Nytro', 'brand_id' => 123],

            ['name' => 'Addict', 'brand_id' => 126],
            ['name' => 'Foil', 'brand_id' => 126],
            ['name' => 'Spark', 'brand_id' => 126],
            ['name' => 'Scale', 'brand_id' => 126],

            ['name' => 'Hightower', 'brand_id' => 133],
            ['name' => 'Tallboy', 'brand_id' => 133],
            ['name' => 'Megatower', 'brand_id' => 133],
            ['name' => 'Nomad', 'brand_id' => 133],
            ['name' => 'Bronson', 'brand_id' => 133],
        ]);
    }
}